@startuml
hide methods

abstract class Event {
    id: UUID <<PK>>
    create_date: TIMESTAMP WITH TIME ZONE <<NOT NULL>>
    name: VARCHAR(100) <<NOT NULL>>
    payload: TEXT
    group_id: VARCHAR(100)
    attempt_count: SMALLINT <<NOT NULL>>
    locked_until: TIMESTAMP WITH TIME ZONE
    prioritet: SMALLINT
    status: VARCHAR(50)>
}

class MaxAttemptsEvent {
    maxAttempts: SMALLINT <<NOT NULL>>
}

class DeadlineEvent {
    maxAttempts: SMALLINT
    deadline_until: TIMESTAMP WITH TIME ZONE <<NOT NULL>>
}

Event <|-- MaxAttemptsEvent
Event <|-- DeadlineEvent
@enduml