@startuml one_instance_processing_eager_cleanup

participant app_scheduler
participant shedlock
participant event_service
participant event_handler
database db

== ShedLock Блокировка ==

app_scheduler -> shedlock : попытка получить блокировку
activate app_scheduler
activate shedlock

shedlock --> app_scheduler : блокировка получена
deactivate shedlock

app_scheduler -> event_service : начать обработку
activate event_service

group transaction
    event_service -> db : поиск событий
    activate db
    db --> event_service : события
    deactivate db
end

== Синхронная обработка ==
loop для каждого события
    event_service -> event_handler : событие для обработки
    activate event_handler

    event_handler -> event_handler : бизнес-логика обработки

    event_handler --> event_service : результат исполнения
    deactivate event_handler

    group transaction
        alt успешно обработано
            event_service -> db : удаление записи 
            activate db
            db --> event_service
            deactivate db
        else неуспешно обработано
            event_service -> db : обработка неуспеха
            activate db
            db --> event_service
            deactivate db
        end
    end
end

event_service --> app_scheduler : завершение обработки
deactivate event_service

app_scheduler -> shedlock : освободить блокировку
activate shedlock
shedlock --> app_scheduler : блокировка освобождена
deactivate shedlock

deactivate app_scheduler

@enduml